//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesos
    {
        public Accesos()
        {
            this.RolAcceso = new HashSet<RolAcceso>();
        }
    
        public int IdAcceso { get; set; }
        public string DetalleAcceso { get; set; }
        public string UrlAcceso { get; set; }
    
        public virtual ICollection<RolAcceso> RolAcceso { get; set; }
    }
}
