//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudades
    {
        public Ciudades()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdCiudad { get; set; }
        public int IdRegion { get; set; }
        public string Ciudad { get; set; }
    
        public virtual Regiones Regiones { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
