//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunas
    {
        public Comunas()
        {
            this.Organizacion = new HashSet<Organizacion>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdComuna { get; set; }
        public int IdProvincia { get; set; }
        public string Comuna { get; set; }
    
        public virtual Provincias Provincias { get; set; }
        public virtual ICollection<Organizacion> Organizacion { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
