//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionCumplimiento
    {
        public int IdEvaluacion { get; set; }
        public Nullable<int> IdAnalisisCausa { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaEv { get; set; }
    
        public virtual AnalisisCausa AnalisisCausa { get; set; }
    }
}
