//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int IdIncidencia { get; set; }
        public Nullable<int> RutCreador { get; set; }
        public Nullable<int> IdTipoIncidencia { get; set; }
        public Nullable<int> IdModoDeteccion { get; set; }
        public System.DateTime FechaIdentificacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEstadoIncidencia { get; set; }
    
        public virtual EstadosIncidencia EstadosIncidencia { get; set; }
        public virtual ModosDeteccion ModosDeteccion { get; set; }
        public virtual TiposIncidencias TiposIncidencias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
