//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organizacion
    {
        public Organizacion()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdOrganizacion { get; set; }
        public int RUN { get; set; }
        public string DV { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public int IdComuna { get; set; }
        public int Telefono { get; set; }
        public bool Estado { get; set; }
    
        public virtual Comunas Comunas { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
