//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincias
    {
        public Provincias()
        {
            this.Comunas = new HashSet<Comunas>();
        }
    
        public int IdProvincia { get; set; }
        public Nullable<int> IdRegion { get; set; }
        public string DescProvincia { get; set; }
    
        public virtual ICollection<Comunas> Comunas { get; set; }
        public virtual Regiones Regiones { get; set; }
    }
}
