//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regiones
    {
        public Regiones()
        {
            this.Ciudades = new HashSet<Ciudades>();
        }
    
        public int IdRegion { get; set; }
        public string Region { get; set; }
    
        public virtual ICollection<Ciudades> Ciudades { get; set; }
    }
}
