//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RolAcceso = new HashSet<RolAcceso>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdRol { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<RolAcceso> RolAcceso { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
