//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModulOtec.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Incidencias = new HashSet<Incidencias>();
        }
    
        public int RUT { get; set; }
        public string DV { get; set; }
        public string Nombres { get; set; }
        public string ApPaterno { get; set; }
        public string ApMaterno { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
        public string PassUsuario { get; set; }
        public Nullable<int> IdRol { get; set; }
        public bool EsRepresentante { get; set; }
        public Nullable<int> IdOrganizacion { get; set; }
        public Nullable<int> IdComuna { get; set; }
        public bool Estado { get; set; }
    
        public virtual Comunas Comunas { get; set; }
        public virtual ICollection<Incidencias> Incidencias { get; set; }
        public virtual Organizacion Organizacion { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
